language: ruby
script: "bundle exec rake test"
cache: bundler
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.6
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
notifications:
  email:
    on_success: always
    on_failure: always
