language: ruby
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 1.9.3
  - 1.9.2
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
notifications:
  email:
    on_success: always
    on_failure: always
